name: protein
channels:
  - pytorch
  - salilab
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=4.13.0=py310hff52083_2
  - conda-package-handling=1.8.1=py310h5764c6d_1
  - cryptography=37.0.2=py310h597c629_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - debugpy=1.6.0=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dssp=3.0.0=h3fd9d12_4
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - freetype=2.12.1=h4a9f257_0
  - future=0.18.3=py310h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py310h06a4308_0
  - jupyter_core=5.3.0=py310hff52083_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=15_linux64_openblas
  - libboost=1.73.0=h28710b8_12
  - libcblas=3.9.0=15_linux64_openblas
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=15_linux64_openblas
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja-base=1.10.2=hd09550d_5
  - numpy-base=1.24.3=py310h375b286_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openh264=2.1.1=h4ff587b_0
  - openmm=7.7.0=py310hccf1d78_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pdbfixer=1.8.1=pyh6c4a22f_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.1=py310h5764c6d_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycosat=0.6.3=py310h5764c6d_1010
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=cpu_py310h92724a6_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=25.0.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py310h6acc77f_1006
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alembic==1.12.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - async-timeout==4.0.2
    - attrs==23.1.0
    - beautifulsoup4==4.12.2
    - biopython==1.81
    - biotite==0.37.0
    - bleach==6.0.0
    - cftime==1.6.2
    - click==8.0.4
    - cmaes==0.10.0
    - cmake==3.26.3
    - colorlog==6.7.0
    - commonmark==0.9.1
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - deepspeed==0.5.9
    - defusedxml==0.7.1
    - dllogger==1.0.0
    - dm-tree==0.1.8
    - docker==6.1.3
    - einops==0.6.1
    - ema-pytorch==0.2.3
    - et-xmlfile==1.1.0
    - fair-esm==2.0.0
    - fastjsonschema==2.16.3
    - filelock==3.12.0
    - flask==2.2.5
    - flask-cors==3.0.10
    - fonttools==4.39.4
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - greenlet==2.0.2
    - gunicorn==20.1.0
    - hjson==3.1.0
    - importlib-metadata==6.7.0
    - ipython==8.13.2
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - lightning-utilities==0.8.0
    - lit==16.0.3
    - mako==1.2.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mistune==2.0.5
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.4.0
    - nbformat==5.8.0
    - netcdf4==1.6.3
    - networkx==3.1
    - ninja==1.11.1
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - omegaconf==2.3.0
    - openpyxl==3.1.2
    - optuna==3.1.0
    - overrides==7.3.1
    - pandas==2.0.1
    - pandocfilters==1.5.0
    - pillow==9.5.0
    - prometheus-client==0.16.0
    - py-cpuinfo==9.0.0
    - pybiolib==1.1.988
    - pycryptodome==3.18.0
    - pyg-lib==0.2.0+pt20cpu
    - pyjwt==2.7.0
    - pyparsing==3.0.9
    - pyproject-toml==0.0.10
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pytorch-lightning==2.0.2
    - pytz==2023.3
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - rdkit==2023.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==12.6.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.20
    - sympy==1.12
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - toml==0.10.2
    - torch==2.0.0
    - torch-cluster==1.6.1+pt20cu118
    - torch-geometric==2.2.0
    - torch-scatter==2.1.1+pt20cu118
    - torch-sparse==0.6.17+pt20cu118
    - torch-spline-conv==1.2.2+pt20cu118
    - torchaudio==2.0.2
    - torchmetrics==0.11.4
    - torchsummary==1.5.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - triton==2.0.0
    - tzdata==2023.3
    - uri-template==1.2.0
    - urllib3==1.26.16
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.3.6
    - widgetsnbextension==4.0.7
    - yarl==1.9.2
    - zipp==3.15.0
prefix: /home/z5174804/miniconda3/envs/protein
